// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv2U5ErHMmGUHvM8kwNDO650CxhBwNK9Y',
    appId: '1:863533584471:web:5499379d7ebe32b5da1312',
    messagingSenderId: '863533584471',
    projectId: 'major-project-d0c57',
    authDomain: 'major-project-d0c57.firebaseapp.com',
    storageBucket: 'major-project-d0c57.firebasestorage.app',
    measurementId: 'G-TFYJ4FSWPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFHyco2qPB9CdnssDwTYrxff6L3jUxOQ',
    appId: '1:863533584471:android:81e0a6c5660ce699da1312',
    messagingSenderId: '863533584471',
    projectId: 'major-project-d0c57',
    storageBucket: 'major-project-d0c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnq09vhxgNlD4xHg7on0nKGmIpVZRhJbM',
    appId: '1:863533584471:ios:9825191315c92dd2da1312',
    messagingSenderId: '863533584471',
    projectId: 'major-project-d0c57',
    storageBucket: 'major-project-d0c57.firebasestorage.app',
    iosBundleId: 'com.example.trailCorrection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnq09vhxgNlD4xHg7on0nKGmIpVZRhJbM',
    appId: '1:863533584471:ios:9825191315c92dd2da1312',
    messagingSenderId: '863533584471',
    projectId: 'major-project-d0c57',
    storageBucket: 'major-project-d0c57.firebasestorage.app',
    iosBundleId: 'com.example.trailCorrection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv2U5ErHMmGUHvM8kwNDO650CxhBwNK9Y',
    appId: '1:863533584471:web:19ab08a15999bae8da1312',
    messagingSenderId: '863533584471',
    projectId: 'major-project-d0c57',
    authDomain: 'major-project-d0c57.firebaseapp.com',
    storageBucket: 'major-project-d0c57.firebasestorage.app',
    measurementId: 'G-BQFTLHF92F',
  );
}
